version: '3'
services:
  address-book:
    build: .
    image: address-book
    container_name: address-book
    restart: unless-stopped
    network_mode: host
    volumes:
      - "${PWD}/logs:/app/storage/logs"
